Django_jisu/pragmatic/articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView


from . import views

app_name = 'articleapp'

urlpatterns = [
    path('<int:searched_code>/',views.summary_result,name='summary_result'),
    path('search/',views.searching_db,name='searching_db')
]

Django_jisu/pragmatic/newsapp/urls.py
from django.urls import path
from . import views


app_name = 'newsapp'

urlpatterns = [
    path('<int:searched_code>/',views.news_graph,name='news_graph'),
    # path('search/',views.news_graph,name="news_main"),
]

Django_jisu/pragmatic/pragmatic/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

import searchapp.views

urlpatterns = [
    path('team3/',searchapp.views.main, name='main'),
    path('team3/articles/', include('articleapp.urls'),name='articleapp'),
    path('team3/news/', include('newsapp.urls'),name='newsapp'),
    path('team3/finanace/', include('financeapp.urls'),name='financeapp'),
    
]

Django_jisu/pragmatic/searchapp/urls.py
from django.urls import path,include

from searchapp.views import main

app_name = 'searchapp'

urlpatterns = [
    path('', main, name='main'),

]

Django_jisu/pragmatic/searchapp/views.py
from django.http import HttpResponse
from django.shortcuts import render
# Create your views here.

def main(request):
    return  render(request,'searchapp/main.html')

def search_page(request):
    return  render(request,'articles/list.html')

Django_jisu/pragmatic/searchapp/templates/searchapp/main.html
<!DOCTYPE html>
<html lang="ko" style="background-image: linear-gradient(to right, rgb(245,245,245) 65%, rgb(220, 0, 0) 35%);">

<style>
    hr {height: 1px;
    color: #dbd9d9;
    background-color: #dbd9d9;
    border: none}

    .left{
        float: left;
        display: inline;
        margin-left: 10px;
    }
    .right{
        float: right;
        display: inline;
        color: rgb(255, 255, 255);
        margin-right: 20px;
    }
    .box {
    color: rgb(241, 8, 8);
    background-color: rgb(245,245,245);
    width: 555px;
    height: 65px;
    padding: 10px;
    border: 1px solid #DBD9D9;
    margin: 15px;
    border-radius: 10px;
    text-align: center;
    }

    .inputcode{
    border:0 solid rgb(245,245,245);
    background-color: rgb(245,245,245);
    width: 400px;
    height: 44px;
    text-align: left;
    text-decoration: none;
    display: inline-block;
    margin-top: 10px;
    font-size: 16px;

    }
    .button {
    background-color: rgb(220, 0, 0); /* Green */
    border: none;
    color: white;
    width: 86px;
    height: 44px;
    border-radius: 5px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
}
</style>



{% load static %}

<head>
    <meta charset="UTF-8">
    <title>ViewPoint</title>

</head>

<body>

    <!-- <div style="visibility: hidden; height: 100px;"></div> -->
    <div style="position: absolute; top: 45%; left: 30%; transform: translate(-50%,-50%);">
        <div style="height: auto; ; border-radius: 1rem; margin:2rem; font-size: 35px;">
            <h1>
                Let's go upward!
            </h1>
        </div>

        <form action="{% url 'articleapp:searching_db' %}" method='POST'>
            {% csrf_token %}
            <div class="box">
                <input class="inputcode" name="stock_search" placeholder="종목코드 입력">
                <button type="submit" class="button"> Search </button>
            </div>
        </form>
    </div>
    <footer>
        <div style="margin-top:-10px; position: fixed; bottom:0; width:100%;">
            <hr>
            <p class="left">2022 SeSAC Project all rights reserved</p>
            <p class="right">About Us</p>
        </div>
    </footer>
</body>
</html>     