Django_jisu/pragmatic/articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView


from . import views

app_name = 'articleapp'

urlpatterns = [
    path('<int:searched_code>/',views.summary_result,name='summary_result'),
    path('search/',views.searching_db,name='searching_db')
]

Django_jisu/pragmatic/financeapp/urls.py
from django.urls import path
from . import views


app_name = 'financeapp'

urlpatterns = [
    path('<int:searched_code>/',views.finance_data,name='finance_data'),
    
]

Django_jisu/pragmatic/newsapp/urls.py
from django.urls import path
from . import views


app_name = 'newsapp'

urlpatterns = [
    path('<int:searched_code>/',views.news_graph,name='news_graph'),
    # path('search/',views.news_graph,name="news_main"),
]

Django_jisu/pragmatic/pragmatic/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

import searchapp.views

urlpatterns = [
    path('team3/',searchapp.views.main, name='main'),
    path('team3/articles/', include('articleapp.urls'),name='articleapp'),
    path('team3/news/', include('newsapp.urls'),name='newsapp'),
    path('team3/finanace/', include('financeapp.urls'),name='financeapp'),
    
]

Django_jisu/pragmatic/templates/base.html
<!DOCTYPE html>
<html lang="ko">

{% include 'head.html' %}

<body style="font-family: 'NanumSquareNeo-Variable';">

    {% include 'header.html' %}


    {% block content %}
    {% endblock %}


    {% include 'footer.html' %}

</body>
</html>

Django_jisu/pragmatic/templates/footer.html
<div class="viewpoint_footer">

    <div class="viewpoint_footer_button">
        <span>공지사항</span> |
        <span>제휴문의</span> |
        <span>서비스 소개</span>
    </div>
    <p1 style="font-size: 25px; margin-left: 20px; cursor: pointer; font-weight: bold;"onclick=location.href="{% url 'main' %}" >view<a style="color: rgb(220, 0, 0);">p</a>oint</p1>

</div>

Django_jisu/pragmatic/templates/head.html
{% load static %}
<style>
    .viewpoint_logo {
        font-family: 'Secular One', sans-serif;
    }
    
    .viewpoint_footer_button {
        font-size: .9rem;
    }
    
    .viewpoint_footer {
        text-align:center;
        margin-top: 2rem;
    }
    
    .viewpoint_header {
        text-align:center;
        margin: 0px;
    }
    
    @media screen and (max-width:500px) {
        html {
            font-size: 13px;
        }
    }
    
    a {
        color: black;
    }
    
    a:hover {
        color: black;
        text-decoration: none;
    }
    
    .viewpoint_header_nav {
        margin: 0 0.5rem;
    }
    
    
    .viewpoint_header_navbar {
        margin: 1rem 0;
    }
    
    .news_box {
        width: 4rem;
        height: 2rem;
        background-color: brown;
    }
</style>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>ViewPoint</title>

    <!--  BOOTSTRAP LINK  -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!--  GOOGLE FONTS LINK  -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Secular+One&display=swap" rel="stylesheet">

    <!--  GOOGLE MATERIAL ICONS  -->
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons" rel="stylesheet">

    <!--  DEFAULT CSS LINK  -->
    <link rel="stylesheet" type="text/css" href="{% static 'base2.css' %}">

    <style>
        @font-face {
            font-family: 'NanumSquareNeo-Variable';
            src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_11-01@1.0/NanumSquareNeo-Variable.woff2') format('woff2');
            font-weight: normal;
            font-style: normal;
        }


        @font-face {
            font-family: 'BMDOHYEON';
            src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_one@1.0/BMDOHYEON.woff') format('woff');
            font-weight: normal;
            font-style: normal;
        }

        @font-face {
            font-family: 'BMHANNAPro';
            src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_seven@1.0/BMHANNAPro.woff') format('woff');
            font-weight: normal;
            font-style: normal;
        }

        @font-face {
            font-family: 'SBAggroB';
            src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2108@1.1/SBAggroB.woff') format('woff');
            font-weight: normal;
            font-style: normal;
        }

        @font-face {
            font-family: 'KOTRA_BOLD-Bold';
            src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_20-10-21@1.1/KOTRA_BOLD-Bold.woff') format('woff');
            font-weight: normal;
            font-style: normal;
        }

        @font-face {
            font-family: 'GmarketSansMedium';
            src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2001@1.1/GmarketSansMedium.woff') format('woff');
            font-weight: normal;
            font-style: normal;
        }

        @font-face {
            font-family: 'BMHANNAAir';
            src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_four@1.0/BMHANNAAir.woff') format('woff');
            font-weight: normal;
            font-style: normal;
        }


    </style>
    <script src="https://code.highcharts.com/stock/highstock.js"></script>
    <script src="https://code.highcharts.com/stock/modules/exporting.js"></script>
    <script src="https://code.highcharts.com/stock/modules/export-data.js"></script>
    <script src="https://code.highcharts.com/stock/modules/accessibility.js"></script>
</head>

Django_jisu/pragmatic/templates/header.html
<style>    
a {
    color: black;
}

a:hover {
    color: black;
    text-decoration: none;
}
</style>
<div style="margin-top: 10px;">
    <p1 style="font-size: 30px; margin-left: 20px; cursor: pointer; font-weight: bold;"onclick=location.href="{% url 'main' %}" >view<a style="color: rgb(220, 0, 0);">p</a>oint</p1>
    <div class="viewpoint_header">
        <div>
            <h1 class="viewpoint_logo">Enterprise <a style="color: rgb(220, 0, 0);">Analysis</a> Contents</h1>
            <p style="color: #888d9a; line-height: 120%; ">뷰포인트에서 제공하는 모든 투자정보는 단순 참고용이며, 추천이나 권유 목적이 아닙니다. 또한 제 3자 데이터 제공업체에서 자료를 제공하므로<br/>
            수신이 지연되거나 일부 정보가 정확하지 않을 수 있으며, 투자 결과에 대한 법적 책임소재의 증빙자료로 사용될 수 없습니다.</p>
        </div>
        <div class="viewpoint_header_navbar" style="display: flex; flex-flow: row nowrap; justify-content: space-around; margin-top: 2%;">
            <a href="{% url 'articleapp:summary_result' searched_code=code %}" class="viewpoint_header_nav" style="flex: 1;color:black">
                <span>기업정보</span>
            </a>
            <a href="{% url 'newsapp:news_graph' searched_code=code %}" class="viewpoint_header_nav" style="flex: 1;color:black">
                <span>뉴스이슈</span>
            </a>
            <a href="{% url 'financeapp:finance_data' searched_code=code %}" class="viewpoint_header_nav" style="flex: 1;color:black">
                <span>재무</span>
            </a>
        </div>
        <div class="line_top"></div>
        <p></p>
        </div>
        
    </div>
</div>

<style>

</style>